controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_fi:
    resource: ../src/Controller/F1RaceResult/
    type: attribute
    prefix: '/api/f1'
