# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Domain\Repository\DriverRepositoryInterface:
        class: App\Infrastructure\Repository\DoctrineDriverRepository

    App\Domain\Repository\RaceRepositoryInterface:
        class: App\Infrastructure\Repository\DoctrineRaceRepository

    App\Domain\Repository\RaceResultRepositoryInterface:
        class: App\Infrastructure\Repository\DoctrineRaceResultRepository
        
    App\Domain\Event\DomainEventDispatcherInterface:
        class: App\Infrastructure\Event\SymfonyDomainEventDispatcher
        
    App\Domain\Specification\:
        resource: '../src/Domain/Specification'
    
    App\Application\CommandHandler\:
        resource: '../src/Application/CommandHandler'
        tags: ['messenger.message_handler']
        
    App\Application\QueryHandler\:
        resource: '../src/Application/QueryHandler'
        tags: [ 'messenger.message_handler' ]

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']
